CREATE DATABASE Notes

USE Notes

CREATE TABLE NOTE
(
  ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Title VARCHAR(50) DEFAULT 'Untitled',
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME,
  Body VARCHAR(1500),
  UNIQUE(Title, CreatedAt)
)

CREATE TABLE TAG
(
  Tag VARCHAR(50) NOT NULL,
  ID INTEGER REFERENCES NOTE(ID),
  PRIMARY KEY(Tag, ID)
)

DROP TABLE TAG
DROP TABLE NOTE
